#!/usr/bin/env node
/**
 * exp-007-ace — ace.mjs
 * ACE CLI: zero-dependency Node ESM. Only node:fs, node:path, node:url,
 * node:child_process, node:crypto.
 *
 * Contract: ace-proagents/PLAN.md §3
 *
 * Commands:
 *   ace init [--name <n>]      scaffold package.json (with ace key) + ace-lock.json + README
 *   ace install [<pkg>]       install from local registry, or git ref
 *   ace list                   installed packages
 *   ace info <pkg>             package detail
 *   ace search <q>             search local registry
 *   ace run                    initState + setStatus running + appendEvent
 *   ace status                 human overview
 *   ace context [--json]       environment context
 *   ace agents                 list agents
 *   ace tasks                  list tasks
 *   ace events [--limit N]     event stream (default 20)
 *   ace stop                   setStatus stopped + appendEvent
 *   ace snapshot               create snapshot
 *   ace restore <id>           restore snapshot
 */

import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import crypto from "node:crypto";
import { execFileSync } from "node:child_process";

// ---------------------------------------------------------------------------
// Dynamic lib imports — degrade gracefully if a worker hasn't landed yet
// ---------------------------------------------------------------------------

const HERE = path.dirname(fileURLToPath(import.meta.url));
const HERE_FILE = fileURLToPath(import.meta.url);

async function loadLib(name) {
  try {
    return await import(path.join(HERE, "lib", name));
  } catch {
    return null;
  }
}

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

function readJson(p) {
  try { return JSON.parse(fs.readFileSync(p, "utf8")); } catch { return null; }
}

function writeJson(p, obj) {
  fs.mkdirSync(path.dirname(p), { recursive: true });
  fs.writeFileSync(p, JSON.stringify(obj, null, 2) + "\n", "utf8");
}

function ensureDir(p) {
  fs.mkdirSync(p, { recursive: true });
}

function printJson(obj) {
  console.log(JSON.stringify(obj, null, 2));
}

function printTable(rows, columns) {
  if (!rows.length) { console.log("  (none)"); return; }
  const widths = columns.map((c) => Math.max(c.header.length, ...rows.map((r) => String(r[c.key] ?? "").length)));
  const header = columns.map((c, i) => c.header.padEnd(widths[i])).join("  ");
  console.log("  " + header);
  console.log("  " + widths.map((w) => "-".repeat(w)).join("  "));
  for (const row of rows) {
    console.log("  " + columns.map((c, i) => String(row[c.key] ?? "").padEnd(widths[i])).join("  "));
  }
}

function gitInfo(dir) {
  try {
    const branch = execFileSync("git", ["rev-parse", "--abbrev-ref", "HEAD"], { cwd: dir, encoding: "utf8" }).trim();
    const commit = execFileSync("git", ["rev-parse", "--short", "HEAD"], { cwd: dir, encoding: "utf8" }).trim();
    return { branch, commit };
  } catch {
    return { branch: null, commit: null };
  }
}

function getTargetDir(args) {
  const nameIdx = args.indexOf("--name");
  if (nameIdx !== -1 && args[nameIdx + 1]) return args[nameIdx + 1];
  return null;
}

// ---------------------------------------------------------------------------
// Command handlers
// ---------------------------------------------------------------------------

async function cmdInit(args) {
  const target = getTargetDir(args) || process.cwd();
  ensureDir(target);

  const pkg = {
    name: path.basename(target),
    version: "0.1.0",
    description: "ACE package",
    license: "MIT",
    type: "module",
    engines: { ace: ">=1.0.0" },
    dependencies: {},
    ace: {
      spec: "ace/v1",
      name: path.basename(target),
      description: `ACE package generated by ace init.`,
      orchestrator: { runtime: "opencode", role: "orchestrator" },
      agents: {
        strategy: "dynamic",
        defaults: { runtime: "opencode" },
        workers: [
          { role: "architect" },
          { role: "frontend" },
          { role: "backend" },
          { role: "tester" },
          { role: "reviewer" },
        ],
      },
      tools: ["git", "github", "filesystem", "terminal"],
      models: { default: { provider: "opencode", model: "fledge-alpha-free" } },
      runtime: { provider: "local" },
      network: { mode: "restricted" },
      filesystem: { mode: "workspace" },
      memory: { persistent: true },
      git: { worktrees: true },
      policies: { require_review_before_merge: true },
      lifecycle: { autonomous: true, restart_on_failure: true },
      entry: {
        manifest: "package.json",
        readme: "README.md",
        main: "ace.mjs",
        lockfile: "ace-lock.json",
      },
    },
  };
  writeJson(path.join(target, "package.json"), pkg);

  writeJson(path.join(target, "ace-lock.json"), { packages: {} });

  const readme = `# ${path.basename(target)}

ACE package generated by \`ace init\`.

## Usage

\`\`\`bash
ace install
ace run
ace status
\`\`\`
`;
  fs.writeFileSync(path.join(target, "README.md"), readme, "utf8");

  // Copy ace.mjs + lib/ so the scaffolded package is self-contained
  fs.copyFileSync(HERE_FILE, path.join(target, "ace.mjs"));
  const libSrc = path.join(HERE, "lib");
  const libDst = path.join(target, "lib");
  if (fs.existsSync(libSrc)) {
    fs.mkdirSync(libDst, { recursive: true });
    for (const f of fs.readdirSync(libSrc)) {
      fs.copyFileSync(path.join(libSrc, f), path.join(libDst, f));
    }
  }

  console.log(`Initialized ACE package in ${target}`);
}

async function cmdInstall(args) {
  const pkg = await loadLib("pkg.mjs");
  const reg = await loadLib("registry.mjs");

  const target = process.cwd();

  if (!args.length) {
    // Install from local registry
    if (!reg) {
      console.log("install: registry not available yet (lib/registry.mjs not found)");
      return;
    }
    const lock = pkg ? pkg.readLockfile(target) : null;
    if (!lock || !Object.keys(lock.packages || {}).length) {
      console.log("install: no packages in lockfile — nothing to install");
      return;
    }
    console.log(`Installing ${Object.keys(lock.packages).length} package(s) from lockfile...`);
    for (const [name, info] of Object.entries(lock.packages)) {
      console.log(`  ${name}@${info.version} — already resolved`);
    }
    console.log("Done.");
    return;
  }

  // Git ref install
  const ref = args[0];
  if (!ref.startsWith("github:") && !ref.startsWith("git+https://")) {
    console.log(`install: unsupported ref "${ref}" — use github:user/repo[#ref] or git+https://...`);
    return;
  }
  if (!reg) {
    console.log("install: registry not available yet (lib/registry.mjs not found)");
    return;
  }
  const result = reg.installGit(ref);
  console.log(`Installed ${result.dir} @ ${result.version}`);
}

async function cmdList() {
  const pkg = await loadLib("pkg.mjs");
  if (!pkg) {
    console.log("list: pkg not available yet (lib/pkg.mjs not found)");
    return;
  }
  const lock = pkg.readLockfile(process.cwd());
  if (!lock || !Object.keys(lock.packages || {}).length) {
    console.log("No packages installed.");
    return;
  }
  const rows = Object.entries(lock.packages).map(([name, info]) => ({
    name,
    version: info.version,
    integrity: info.integrity ? info.integrity.slice(0, 16) + "…" : "—",
  }));
  printTable(rows, [
    { header: "NAME", key: "name" },
    { header: "VERSION", key: "version" },
    { header: "INTEGRITY", key: "integrity" },
  ]);
}

async function cmdInfo(args) {
  const name = args[0];
  if (!name) { console.log("usage: ace info <pkg>"); return; }

  const reg = await loadLib("registry.mjs");
  const pkg = await loadLib("pkg.mjs");

  if (reg) {
    const info = reg.infoLocal(name);
    if (info) {
      console.log(`Package: ${info.name}@${info.version}`);
      console.log(`Description: ${info.description || "—"}`);
      console.log(`Orchestrator: ${info.orchestrator || "—"}`);
      console.log(`Agents: ${info.agents?.length || 0}`);
      console.log(`Tools: ${info.tools?.join(", ") || "—"}`);
      console.log(`Runtime: ${info.runtime || "—"}`);
      console.log(`Repository: ${info.repository || "—"}`);
      console.log(`Dependencies: ${info.dependencies?.join(", ") || "—"}`);
      return;
    }
  }

  if (pkg) {
    const lock = pkg.readLockfile(process.cwd());
    const entry = lock?.packages?.[name];
    if (entry) {
      console.log(`Package: ${name}@${entry.version}`);
      console.log(`Integrity: ${entry.integrity || "—"}`);
      return;
    }
  }

  console.log(`Package "${name}" not found.`);
}

async function cmdSearch(args) {
  const q = args[0];
  if (!q) { console.log("usage: ace search <query>"); return; }

  const reg = await loadLib("registry.mjs");
  if (!reg) {
    console.log("search: registry not available yet (lib/registry.mjs not found)");
    return;
  }
  const results = reg.searchLocal(q);
  if (!results.length) {
    console.log(`No results for "${q}".`);
    return;
  }
  const rows = results.map((r) => ({
    name: r.name,
    version: r.version,
    description: (r.description || "").slice(0, 60),
    score: r.score,
  }));
  printTable(rows, [
    { header: "NAME", key: "name" },
    { header: "VERSION", key: "version" },
    { header: "DESCRIPTION", key: "description" },
    { header: "SCORE", key: "score" },
  ]);
}

async function cmdRun() {
  const rt = await loadLib("runtime.mjs");
  if (!rt) {
    console.log("run: runtime not available yet (lib/runtime.mjs not found)");
    return;
  }
  const dir = process.cwd();
  rt.initState(dir);
  rt.setStatus(dir, "running");
  rt.appendEvent(dir, {
    id: `evt_${crypto.randomBytes(6).toString("hex")}`,
    timestamp: new Date().toISOString(),
    type: "orchestrator.started",
    actor: "orchestrator",
    task: null,
    metadata: {},
  });
  console.log("Runtime started.");
}

async function cmdStatus() {
  const rt = await loadLib("runtime.mjs");
  if (!rt) {
    console.log("status: runtime not available yet (lib/runtime.mjs not found)");
    return;
  }
  const dir = process.cwd();
  const state = rt.getState(dir);
  const agents = rt.getAgents(dir);
  const tasks = rt.getTasks(dir);
  const git = gitInfo(dir);

  console.log(`Status: ${state.status}`);
  console.log(`Updated: ${state.updatedAt}`);
  console.log(`Orchestrator: ${state.active?.agent || "—"} (${state.active?.status || "—"})`);
  console.log(`Agents: ${agents.length}`);
  console.log(`Tasks: ${tasks.length}`);
  console.log(`Git: ${git.branch || "—"} @ ${git.commit || "—"}`);
  console.log(`Resources: ${agents.filter((a) => a.status === "working").length} working, ${agents.filter((a) => a.status === "idle").length} idle`);
}

async function cmdContext(args) {
  const rt = await loadLib("runtime.mjs");
  if (!rt) {
    console.log("context: runtime not available yet (lib/runtime.mjs not found)");
    return;
  }
  const dir = process.cwd();
  const ctx = rt.getContext(dir);
  if (args.includes("--json")) {
    printJson(ctx);
  } else {
    console.log(`Host: ${ctx.host || "—"}`);
    console.log(`Runtime: ${ctx.runtime || "—"}`);
    console.log(`Project: ${ctx.project || "—"}`);
    console.log(`Git: ${ctx.git?.branch || "—"} @ ${ctx.git?.commit || "—"}`);
    console.log(`Tools: ${ctx.tools?.join(", ") || "—"}`);
    console.log(`Resources: ${JSON.stringify(ctx.resources || {})}`);
  }
}

async function cmdAgents() {
  const rt = await loadLib("runtime.mjs");
  if (!rt) {
    console.log("agents: runtime not available yet (lib/runtime.mjs not found)");
    return;
  }
  const agents = rt.getAgents(process.cwd());
  if (!agents.length) { console.log("No agents."); return; }
  const rows = agents.map((a) => ({
    id: a.id,
    role: a.role,
    status: a.status,
    task: a.task || "—",
  }));
  printTable(rows, [
    { header: "ID", key: "id" },
    { header: "ROLE", key: "role" },
    { header: "STATUS", key: "status" },
    { header: "TASK", key: "task" },
  ]);
}

async function cmdTasks() {
  const rt = await loadLib("runtime.mjs");
  if (!rt) {
    console.log("tasks: runtime not available yet (lib/runtime.mjs not found)");
    return;
  }
  const tasks = rt.getTasks(process.cwd());
  if (!tasks.length) { console.log("No tasks."); return; }
  const rows = tasks.map((t) => ({
    id: t.id,
    title: (t.title || "").slice(0, 40),
    status: t.status,
    assigned: t.assignedTo || "—",
    priority: t.priority || "—",
  }));
  printTable(rows, [
    { header: "ID", key: "id" },
    { header: "TITLE", key: "title" },
    { header: "STATUS", key: "status" },
    { header: "ASSIGNED", key: "assigned" },
    { header: "PRIORITY", key: "priority" },
  ]);
}

async function cmdEvents(args) {
  const rt = await loadLib("runtime.mjs");
  if (!rt) {
    console.log("events: runtime not available yet (lib/runtime.mjs not found)");
    return;
  }
  const limitIdx = args.indexOf("--limit");
  const limit = limitIdx !== -1 && args[limitIdx + 1] ? parseInt(args[limitIdx + 1], 10) : 20;

  const eventsPath = path.join(process.cwd(), ".ace", "events.jsonl");
  if (!fs.existsSync(eventsPath)) { console.log("No events yet."); return; }
  const lines = fs.readFileSync(eventsPath, "utf8").trim().split("\n").filter(Boolean);
  const recent = lines.slice(-limit);
  for (const line of recent) {
    const ev = JSON.parse(line);
    console.log(`  [${ev.timestamp}] ${ev.type} — ${ev.actor}${ev.task ? ` (task: ${ev.task})` : ""}`);
  }
}

async function cmdStop() {
  const rt = await loadLib("runtime.mjs");
  if (!rt) {
    console.log("stop: runtime not available yet (lib/runtime.mjs not found)");
    return;
  }
  const dir = process.cwd();
  rt.setStatus(dir, "stopped");
  rt.appendEvent(dir, {
    id: `evt_${crypto.randomBytes(6).toString("hex")}`,
    timestamp: new Date().toISOString(),
    type: "orchestrator.stopped",
    actor: "orchestrator",
    task: null,
    metadata: {},
  });
  console.log("Runtime stopped.");
}

async function cmdSnapshot() {
  const rt = await loadLib("runtime.mjs");
  if (!rt) {
    console.log("snapshot: runtime not available yet (lib/runtime.mjs not found)");
    return;
  }
  const snap = rt.snapshot(process.cwd());
  console.log(`Snapshot created: ${snap.id} at ${snap.at}`);
}

async function cmdRestore(args) {
  const id = args[0];
  if (!id) { console.log("usage: ace restore <id>"); return; }
  const rt = await loadLib("runtime.mjs");
  if (!rt) {
    console.log("restore: runtime not available yet (lib/runtime.mjs not found)");
    return;
  }
  rt.restore(process.cwd(), id);
  console.log(`Restored snapshot ${id}.`);
}

// ---------------------------------------------------------------------------
// Phase 7-8 commands
// ---------------------------------------------------------------------------

async function cmdCompose(args) {
  const pkg = await loadLib("pkg.mjs");
  if (!pkg) {
    console.log("compose: pkg not available yet (lib/pkg.mjs not found)");
    return;
  }
  const dir = process.cwd();
  const loaded = pkg.loadPackage(dir);
  const spec = loaded.workspace;
  if (!spec) {
    console.log("compose: no ace spec found in package.json");
    return;
  }

  // Resolve extends from local registry if present
  const reg = await loadLib("registry.mjs");
  const deps = [];
  if (Array.isArray(spec.extends) && reg) {
    for (const name of spec.extends) {
      const info = reg.infoLocal(name.replace(/^@ace\//, ""));
      if (info) deps.push(info);
    }
  }

  const composed = pkg.compose(spec, deps);
  if (args.includes("--json")) {
    printJson(composed);
  } else {
    // Simple YAML output (key: value, nested via indent)
    console.log(JSON.stringify(composed, null, 2));
  }
}

async function cmdDoctor(args) {
  const pkg = await loadLib("pkg.mjs");
  if (!pkg || typeof pkg.doctor !== "function") {
    console.log("doctor: not available yet (lib/pkg.mjs doctor not implemented)");
    return;
  }
  const result = pkg.doctor(process.cwd());
  if (args.includes("--json")) {
    printJson(result);
    return;
  }
  console.log(`Doctor: ${result.ok ? "OK" : "FAIL"}`);
  for (const check of result.checks || []) {
    console.log(`  ${check.ok ? "✓" : "✗"} ${check.name}: ${check.detail || ""}`);
  }
  for (const w of result.warnings || []) {
    console.log(`  ! ${w}`);
  }
}

async function cmdUpdate() {
  const pkg = await loadLib("pkg.mjs");
  if (!pkg || typeof pkg.resolveDependencies !== "function") {
    console.log("update: not available yet (lib/pkg.mjs resolveDependencies not implemented)");
    return;
  }
  const dir = process.cwd();
  const loaded = pkg.loadPackage(dir);
  const manifest = loaded.manifest;
  const reg = await loadLib("registry.mjs");
  const result = pkg.resolveDependencies(manifest, reg);
  if (!result.ok) {
    console.log("update: dependency conflicts detected:");
    for (const c of result.conflicts || []) console.log(`  ${c}`);
    return;
  }
  console.log(`update: resolved ${Object.keys(result.graph || {}).length} package(s)`);
  for (const [name, info] of Object.entries(result.graph || {})) {
    console.log(`  ${name}@${info.version}`);
  }
}

async function cmdUninstall(args) {
  const name = args[0];
  if (!name) { console.log("usage: ace uninstall <pkg>"); return; }
  const pkg = await loadLib("pkg.mjs");
  if (!pkg) {
    console.log("uninstall: pkg not available yet (lib/pkg.mjs not found)");
    return;
  }
  const dir = process.cwd();
  const loaded = pkg.loadPackage(dir);
  const manifest = loaded.manifest;
  if (!manifest.dependencies || !manifest.dependencies[name]) {
    console.log(`uninstall: "${name}" is not a dependency`);
    return;
  }
  delete manifest.dependencies[name];
  writeJson(path.join(dir, "package.json"), manifest);
  console.log(`Uninstalled ${name}.`);
}

async function cmdSecretSet(args) {
  const name = args[0];
  if (!name) { console.log("usage: ace secret set <name>"); return; }
  const dir = process.cwd();
  const secretsDir = path.join(dir, ".ace", "secrets");
  ensureDir(secretsDir);

  // Read value from stdin without echoing
  const value = await new Promise((resolve) => {
    if (process.stdin.isTTY) {
      // Interactive: use readline with muted output
      import("node:readline").then(({ createInterface }) => {
        const rl = createInterface({ input: process.stdin, output: process.stdout });
        rl.question(`Enter value for ${name}: `, (answer) => {
          rl.close();
          resolve(answer.trim());
        });
      });
    } else {
      // Piped: read all stdin
      let buf = "";
      process.stdin.setEncoding("utf8");
      process.stdin.on("data", (chunk) => { buf += chunk; });
      process.stdin.on("end", () => resolve(buf.trim()));
    }
  });

  if (!value) {
    console.log("secret set: empty value — aborted");
    return;
  }
  fs.writeFileSync(path.join(secretsDir, name), value + "\n", { mode: 0o600 });
  console.log(`Secret "${name}" stored in .ace/secrets/${name}`);
}

async function cmdActivity() {
  const rt = await loadLib("runtime.mjs");
  if (!rt) {
    console.log("activity: runtime not available yet (lib/runtime.mjs not found)");
    return;
  }
  const dir = process.cwd();
  const agents = rt.getAgents(dir);
  const tasks = rt.getTasks(dir);

  const working = agents.filter((a) => a.status === "working");
  const idle = agents.filter((a) => a.status === "idle");
  const queued = tasks.filter((t) => t.status === "queued" || t.status === "pending");

  console.log("NOW:");
  if (!working.length) console.log("  (no agents working)");
  for (const a of working) console.log(`  ${a.id} (${a.role}) — task: ${a.task || "—"}`);

  console.log("NEXT:");
  if (!queued.length) console.log("  (no tasks queued)");
  for (const t of queued) console.log(`  ${t.id} — ${t.title} (priority: ${t.priority || "—"})`);

  if (idle.length) console.log(`IDLE: ${idle.length} agent(s)`);
}

async function cmdLogs(args) {
  const limitIdx = args.indexOf("--limit");
  const limit = limitIdx !== -1 && args[limitIdx + 1] ? parseInt(args[limitIdx + 1], 10) : 20;

  const eventsPath = path.join(process.cwd(), ".ace", "events.jsonl");
  if (!fs.existsSync(eventsPath)) { console.log("No logs yet."); return; }
  const lines = fs.readFileSync(eventsPath, "utf8").trim().split("\n").filter(Boolean);
  const recent = lines.slice(-limit);
  for (const line of recent) {
    const ev = JSON.parse(line);
    console.log(`  [${ev.timestamp}] ${ev.type} — ${ev.actor}${ev.task ? ` (task: ${ev.task})` : ""}`);
  }
}

async function cmdRestart() {
  const rt = await loadLib("runtime.mjs");
  if (!rt) {
    console.log("restart: runtime not available yet (lib/runtime.mjs not found)");
    return;
  }
  const dir = process.cwd();
  const statePath = path.join(dir, ".ace", "state.json");
  if (typeof rt.recover === "function" && fs.existsSync(statePath)) {
    rt.recover(dir);
  }
  rt.setStatus(dir, "ready");
  rt.appendEvent(dir, {
    id: `evt_${crypto.randomBytes(6).toString("hex")}`,
    timestamp: new Date().toISOString(),
    type: "orchestrator.restarted",
    actor: "orchestrator",
    task: null,
    metadata: {},
  });
  console.log("Runtime restarted.");
}

// ---------------------------------------------------------------------------
// Router
// ---------------------------------------------------------------------------

const COMMANDS = {
  init: cmdInit,
  install: cmdInstall,
  list: cmdList,
  info: cmdInfo,
  search: cmdSearch,
  run: cmdRun,
  status: cmdStatus,
  context: cmdContext,
  agents: cmdAgents,
  tasks: cmdTasks,
  events: cmdEvents,
  stop: cmdStop,
  snapshot: cmdSnapshot,
  restore: cmdRestore,
  compose: cmdCompose,
  doctor: cmdDoctor,
  update: cmdUpdate,
  uninstall: cmdUninstall,
  activity: cmdActivity,
  logs: cmdLogs,
  restart: cmdRestart,
};

async function main() {
  const args = process.argv.slice(2);
  const cmd = args[0];

  if (!cmd || cmd === "--help" || cmd === "-h" || cmd === "help") {
    console.log(`ACE — Agentic Compute Environment CLI

Usage: ace <command> [options]

Commands:
  init [--name <n>]      Scaffold package.json (with ace key) + ace-lock.json + README
  install [<pkg>]       Install from local registry, or git ref
  list                   List installed packages
  info <pkg>             Show package detail
  search <q>             Search local registry
  run                    Start runtime
  status                 Show human-readable status
  context [--json]       Show environment context
  agents                 List agents
  tasks                  List tasks
  events [--limit N]     Show event stream (default 20)
  stop                   Stop runtime
  snapshot               Create snapshot
  restore <id>           Restore snapshot
  compose [--json]       Print composed spec (extends + overrides + capabilities)
  doctor [--json]        Environment diagnostics
  update                 Update dependencies per version constraints
  uninstall <pkg>        Remove a dependency from package.json
  secret set <name>      Inject a secret into .ace/secrets/<name>
  activity               NOW / NEXT activity stream
  logs [--limit N]       Tail the event log (default 20)
  restart                Recover + continue

Options:
  --name <n>             Target directory for init
  --limit N              Limit for events/logs command
  --json                 JSON output for context/compose/doctor
`);
    return;
  }

  const handler = COMMANDS[cmd];
  if (!handler) {
    // Handle two-word commands: ace secret set <name>
    if (cmd === "secret" && args[1] === "set") {
      try { await cmdSecretSet(args.slice(2)); } catch (err) { console.error(`ace secret set: ${err.message}`); process.exitCode = 1; }
      return;
    }
    console.log(`Unknown command: ${cmd}`);
    console.log("Run `ace --help` for usage.");
    process.exitCode = 1;
    return;
  }

  try {
    await handler(args.slice(1));
  } catch (err) {
    console.error(`ace ${cmd}: ${err.message}`);
    process.exitCode = 1;
  }
}

main();
