#!/usr/bin/env node
/**
 * exp-007-ace — ace.mjs
 * ACE CLI: zero-dependency Node ESM. Only node:fs, node:path, node:url,
 * node:child_process, node:crypto.
 *
 * Contract: ace-proagents/PLAN.md §3
 *
 * Commands:
 *   ace init [--name <n>]      scaffold package.json (with ace key) + ace-lock.json + README
 *   ace install [<pkg>]       install from local registry, or git ref
 *   ace list                   installed packages
 *   ace info <pkg>             package detail
 *   ace search <q>             search local registry
 *   ace run                    initState + setStatus running + appendEvent
 *   ace status                 human overview
 *   ace context [--json]       environment context
 *   ace agents                 list agents
 *   ace tasks                  list tasks
 *   ace events [--limit N]     event stream (default 20)
 *   ace stop                   setStatus stopped + appendEvent
 *   ace snapshot               create snapshot
 *   ace restore <id>           restore snapshot
 *   ace verify [--json]        run configured verification (lint/typecheck/test/build)
 *   ace autopilot [status|on|run|off]  the always-on loop (PAW parity)
 */

import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import crypto from "node:crypto";
import { execFileSync, spawn, spawnSync } from "node:child_process";

// ---------------------------------------------------------------------------
// Dynamic lib imports — degrade gracefully if a worker hasn't landed yet
// ---------------------------------------------------------------------------

const HERE = path.dirname(fileURLToPath(import.meta.url));
const HERE_FILE = fileURLToPath(import.meta.url);

async function loadLib(name) {
  try {
    return await import(path.join(HERE, "lib", name));
  } catch {
    return null;
  }
}

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

function readJson(p) {
  try { return JSON.parse(fs.readFileSync(p, "utf8")); } catch { return null; }
}

function writeJson(p, obj) {
  fs.mkdirSync(path.dirname(p), { recursive: true });
  fs.writeFileSync(p, JSON.stringify(obj, null, 2) + "\n", "utf8");
}

function ensureDir(p) {
  fs.mkdirSync(p, { recursive: true });
}

function printJson(obj) {
  console.log(JSON.stringify(obj, null, 2));
}

function printTable(rows, columns) {
  if (!rows.length) { console.log("  (none)"); return; }
  const widths = columns.map((c) => Math.max(c.header.length, ...rows.map((r) => String(r[c.key] ?? "").length)));
  const header = columns.map((c, i) => c.header.padEnd(widths[i])).join("  ");
  console.log("  " + header);
  console.log("  " + widths.map((w) => "-".repeat(w)).join("  "));
  for (const row of rows) {
    console.log("  " + columns.map((c, i) => String(row[c.key] ?? "").padEnd(widths[i])).join("  "));
  }
}

function gitInfo(dir) {
  try {
    const branch = execFileSync("git", ["rev-parse", "--abbrev-ref", "HEAD"], { cwd: dir, encoding: "utf8" }).trim();
    const commit = execFileSync("git", ["rev-parse", "--short", "HEAD"], { cwd: dir, encoding: "utf8" }).trim();
    return { branch, commit };
  } catch {
    return { branch: null, commit: null };
  }
}

function getTargetDir(args) {
  const nameIdx = args.indexOf("--name");
  if (nameIdx !== -1 && args[nameIdx + 1]) return args[nameIdx + 1];
  return null;
}

// ---------------------------------------------------------------------------
// Command handlers
// ---------------------------------------------------------------------------

async function cmdInit(args) {
  const target = getTargetDir(args) || process.cwd();
  ensureDir(target);

  const pkg = {
    name: path.basename(target),
    version: "0.1.0",
    description: "ACE package",
    license: "MIT",
    type: "module",
    engines: { ace: ">=1.0.0" },
    dependencies: {},
    ace: {
      spec: "ace/v1",
      name: path.basename(target),
      description: `ACE package generated by ace init.`,
      orchestrator: { runtime: "opencode", role: "orchestrator" },
      agents: {
        strategy: "dynamic",
        defaults: { runtime: "opencode" },
        workers: [
          { role: "architect" },
          { role: "frontend" },
          { role: "backend" },
          { role: "tester" },
          { role: "reviewer" },
        ],
      },
      tools: ["git", "github", "filesystem", "terminal"],
      models: { default: { provider: "opencode", model: "fledge-alpha-free" } },
      runtime: { provider: "local" },
      network: { mode: "restricted" },
      filesystem: { mode: "workspace" },
      memory: { persistent: true },
      git: { worktrees: true },
      policies: { require_review_before_merge: true },
      lifecycle: { autonomous: true, restart_on_failure: true },
      entry: {
        manifest: "package.json",
        readme: "README.md",
        main: "ace.mjs",
        lockfile: "ace-lock.json",
      },
    },
  };
  writeJson(path.join(target, "package.json"), pkg);

  writeJson(path.join(target, "ace-lock.json"), { packages: {} });

  const readme = `# ${path.basename(target)}

ACE package generated by \`ace init\`.

## Usage

\`\`\`bash
ace install
ace run
ace status
\`\`\`
`;
  fs.writeFileSync(path.join(target, "README.md"), readme, "utf8");

  // Copy ace.mjs + lib/ so the scaffolded package is self-contained
  fs.copyFileSync(HERE_FILE, path.join(target, "ace.mjs"));
  const libSrc = path.join(HERE, "lib");
  const libDst = path.join(target, "lib");
  if (fs.existsSync(libSrc)) {
    fs.mkdirSync(libDst, { recursive: true });
    for (const f of fs.readdirSync(libSrc)) {
      fs.copyFileSync(path.join(libSrc, f), path.join(libDst, f));
    }
  }

  console.log(`Initialized ACE package in ${target}`);
}

async function cmdInstall(args) {
  const pkg = await loadLib("pkg.mjs");
  const reg = await loadLib("registry.mjs");

  const target = process.cwd();

  if (!args.length) {
    // Install from local registry
    if (!reg) {
      console.log("install: registry not available yet (lib/registry.mjs not found)");
      return;
    }
    const lock = pkg ? pkg.readLockfile(target) : null;
    if (!lock || !Object.keys(lock.packages || {}).length) {
      console.log("install: no packages in lockfile — nothing to install");
      return;
    }
    console.log(`Installing ${Object.keys(lock.packages).length} package(s) from lockfile...`);
    for (const [name, info] of Object.entries(lock.packages)) {
      console.log(`  ${name}@${info.version} — already resolved`);
    }
    console.log("Done.");
    return;
  }

  // Git ref install
  const ref = args[0];
  if (!ref.startsWith("github:") && !ref.startsWith("git+https://")) {
    console.log(`install: unsupported ref "${ref}" — use github:user/repo[#ref] or git+https://...`);
    return;
  }
  if (!reg) {
    console.log("install: registry not available yet (lib/registry.mjs not found)");
    return;
  }
  const result = reg.installGit(ref);
  console.log(`Installed ${result.dir} @ ${result.version}`);
}

async function cmdList() {
  const pkg = await loadLib("pkg.mjs");
  if (!pkg) {
    console.log("list: pkg not available yet (lib/pkg.mjs not found)");
    return;
  }
  const lock = pkg.readLockfile(process.cwd());
  if (!lock || !Object.keys(lock.packages || {}).length) {
    console.log("No packages installed.");
    return;
  }
  const rows = Object.entries(lock.packages).map(([name, info]) => ({
    name,
    version: info.version,
    integrity: info.integrity ? info.integrity.slice(0, 16) + "…" : "—",
  }));
  printTable(rows, [
    { header: "NAME", key: "name" },
    { header: "VERSION", key: "version" },
    { header: "INTEGRITY", key: "integrity" },
  ]);
}

async function cmdInfo(args) {
  const name = args[0];
  if (!name) { console.log("usage: ace info <pkg>"); return; }

  const reg = await loadLib("registry.mjs");
  const pkg = await loadLib("pkg.mjs");

  if (reg) {
    const info = reg.infoLocal(name);
    if (info) {
      console.log(`Package: ${info.name}@${info.version}`);
      console.log(`Description: ${info.description || "—"}`);
      console.log(`Orchestrator: ${info.orchestrator || "—"}`);
      console.log(`Agents: ${info.agents?.length || 0}`);
      console.log(`Tools: ${info.tools?.join(", ") || "—"}`);
      console.log(`Runtime: ${info.runtime || "—"}`);
      console.log(`Repository: ${info.repository || "—"}`);
      console.log(`Dependencies: ${info.dependencies?.join(", ") || "—"}`);
      return;
    }
  }

  if (pkg) {
    const lock = pkg.readLockfile(process.cwd());
    const entry = lock?.packages?.[name];
    if (entry) {
      console.log(`Package: ${name}@${entry.version}`);
      console.log(`Integrity: ${entry.integrity || "—"}`);
      return;
    }
  }

  console.log(`Package "${name}" not found.`);
}

async function cmdSearch(args) {
  const q = args[0];
  if (!q) { console.log("usage: ace search <query>"); return; }

  const reg = await loadLib("registry.mjs");
  if (!reg) {
    console.log("search: registry not available yet (lib/registry.mjs not found)");
    return;
  }
  const results = reg.searchLocal(q);
  if (!results.length) {
    console.log(`No results for "${q}".`);
    return;
  }
  const rows = results.map((r) => ({
    name: r.name,
    version: r.version,
    description: (r.description || "").slice(0, 60),
    score: r.score,
  }));
  printTable(rows, [
    { header: "NAME", key: "name" },
    { header: "VERSION", key: "version" },
    { header: "DESCRIPTION", key: "description" },
    { header: "SCORE", key: "score" },
  ]);
}

async function cmdRun() {
  const rt = await loadLib("runtime.mjs");
  if (!rt) {
    console.log("run: runtime not available yet (lib/runtime.mjs not found)");
    return;
  }
  const dir = process.cwd();
  rt.initState(dir);
  rt.setStatus(dir, "running");
  rt.appendEvent(dir, {
    id: `evt_${crypto.randomBytes(6).toString("hex")}`,
    timestamp: new Date().toISOString(),
    type: "orchestrator.started",
    actor: "orchestrator",
    task: null,
    metadata: {},
  });
  console.log("Runtime started.");
}

async function cmdStatus() {
  const rt = await loadLib("runtime.mjs");
  if (!rt) {
    console.log("status: runtime not available yet (lib/runtime.mjs not found)");
    return;
  }
  const dir = process.cwd();
  const state = rt.getState(dir);
  const agents = rt.getAgents(dir);
  const tasks = rt.getTasks(dir);
  const git = gitInfo(dir);

  console.log(`Status: ${state.status}`);
  console.log(`Updated: ${state.updatedAt}`);
  console.log(`Orchestrator: ${state.active?.agent || "—"} (${state.active?.status || "—"})`);
  console.log(`Agents: ${agents.length}`);
  console.log(`Tasks: ${tasks.length}`);
  console.log(`Git: ${git.branch || "—"} @ ${git.commit || "—"}`);
  console.log(`Resources: ${agents.filter((a) => a.status === "working").length} working, ${agents.filter((a) => a.status === "idle").length} idle`);
}

async function cmdContext(args) {
  const rt = await loadLib("runtime.mjs");
  if (!rt) {
    console.log("context: runtime not available yet (lib/runtime.mjs not found)");
    return;
  }
  const dir = process.cwd();
  const ctx = rt.getContext(dir);
  if (args.includes("--json")) {
    printJson(ctx);
  } else {
    console.log(`Host: ${ctx.host || "—"}`);
    console.log(`Runtime: ${ctx.runtime || "—"}`);
    console.log(`Project: ${ctx.project || "—"}`);
    console.log(`Git: ${ctx.git?.branch || "—"} @ ${ctx.git?.commit || "—"}`);
    console.log(`Tools: ${ctx.tools?.join(", ") || "—"}`);
    console.log(`Resources: ${JSON.stringify(ctx.resources || {})}`);
  }
}

async function cmdAgents() {
  const rt = await loadLib("runtime.mjs");
  if (!rt) {
    console.log("agents: runtime not available yet (lib/runtime.mjs not found)");
    return;
  }
  const agents = rt.getAgents(process.cwd());
  if (!agents.length) { console.log("No agents."); return; }
  const rows = agents.map((a) => ({
    id: a.id,
    role: a.role,
    status: a.status,
    task: a.task || "—",
  }));
  printTable(rows, [
    { header: "ID", key: "id" },
    { header: "ROLE", key: "role" },
    { header: "STATUS", key: "status" },
    { header: "TASK", key: "task" },
  ]);
}

async function cmdTasks() {
  const rt = await loadLib("runtime.mjs");
  if (!rt) {
    console.log("tasks: runtime not available yet (lib/runtime.mjs not found)");
    return;
  }
  const tasks = rt.getTasks(process.cwd());
  if (!tasks.length) { console.log("No tasks."); return; }
  const rows = tasks.map((t) => ({
    id: t.id,
    title: (t.title || "").slice(0, 40),
    status: t.status,
    assigned: t.assignedTo || "—",
    priority: t.priority || "—",
  }));
  printTable(rows, [
    { header: "ID", key: "id" },
    { header: "TITLE", key: "title" },
    { header: "STATUS", key: "status" },
    { header: "ASSIGNED", key: "assigned" },
    { header: "PRIORITY", key: "priority" },
  ]);
}

async function cmdEvents(args) {
  const rt = await loadLib("runtime.mjs");
  if (!rt) {
    console.log("events: runtime not available yet (lib/runtime.mjs not found)");
    return;
  }
  const limitIdx = args.indexOf("--limit");
  const limit = limitIdx !== -1 && args[limitIdx + 1] ? parseInt(args[limitIdx + 1], 10) : 20;

  const eventsPath = path.join(process.cwd(), ".ace", "events.jsonl");
  if (!fs.existsSync(eventsPath)) { console.log("No events yet."); return; }
  const lines = fs.readFileSync(eventsPath, "utf8").trim().split("\n").filter(Boolean);
  const recent = lines.slice(-limit);
  for (const line of recent) {
    const ev = JSON.parse(line);
    console.log(`  [${ev.timestamp}] ${ev.type} — ${ev.actor}${ev.task ? ` (task: ${ev.task})` : ""}`);
  }
}

async function cmdStop() {
  const rt = await loadLib("runtime.mjs");
  if (!rt) {
    console.log("stop: runtime not available yet (lib/runtime.mjs not found)");
    return;
  }
  const dir = process.cwd();
  rt.setStatus(dir, "stopped");
  rt.appendEvent(dir, {
    id: `evt_${crypto.randomBytes(6).toString("hex")}`,
    timestamp: new Date().toISOString(),
    type: "orchestrator.stopped",
    actor: "orchestrator",
    task: null,
    metadata: {},
  });
  console.log("Runtime stopped.");
}

async function cmdSnapshot() {
  const rt = await loadLib("runtime.mjs");
  if (!rt) {
    console.log("snapshot: runtime not available yet (lib/runtime.mjs not found)");
    return;
  }
  const snap = rt.snapshot(process.cwd());
  console.log(`Snapshot created: ${snap.id} at ${snap.at}`);
}

async function cmdRestore(args) {
  const id = args[0];
  if (!id) { console.log("usage: ace restore <id>"); return; }
  const rt = await loadLib("runtime.mjs");
  if (!rt) {
    console.log("restore: runtime not available yet (lib/runtime.mjs not found)");
    return;
  }
  rt.restore(process.cwd(), id);
  console.log(`Restored snapshot ${id}.`);
}

// ---------------------------------------------------------------------------
// Phase 7-8 commands
// ---------------------------------------------------------------------------

async function cmdCompose(args) {
  const pkg = await loadLib("pkg.mjs");
  if (!pkg) {
    console.log("compose: pkg not available yet (lib/pkg.mjs not found)");
    return;
  }
  const dir = process.cwd();
  const loaded = pkg.loadPackage(dir);
  const spec = loaded.workspace;
  if (!spec) {
    console.log("compose: no ace spec found in package.json");
    return;
  }

  // Resolve extends from local registry if present
  const reg = await loadLib("registry.mjs");
  const deps = [];
  if (Array.isArray(spec.extends) && reg) {
    for (const name of spec.extends) {
      const info = reg.infoLocal(name.replace(/^@ace\//, ""));
      if (info) deps.push(info);
    }
  }

  const composed = pkg.compose(spec, deps);
  if (args.includes("--json")) {
    printJson(composed);
  } else {
    // Simple YAML output (key: value, nested via indent)
    console.log(JSON.stringify(composed, null, 2));
  }
}

async function cmdDoctor(args) {
  const pkg = await loadLib("pkg.mjs");
  if (!pkg || typeof pkg.doctor !== "function") {
    console.log("doctor: not available yet (lib/pkg.mjs doctor not implemented)");
    return;
  }
  const result = pkg.doctor(process.cwd());
  if (args.includes("--json")) {
    printJson(result);
    return;
  }
  console.log(`Doctor: ${result.ok ? "OK" : "FAIL"}`);
  for (const check of result.checks || []) {
    console.log(`  ${check.ok ? "✓" : "✗"} ${check.name}: ${check.detail || ""}`);
  }
  for (const w of result.warnings || []) {
    console.log(`  ! ${w}`);
  }
}

async function cmdUpdate() {
  const pkg = await loadLib("pkg.mjs");
  if (!pkg || typeof pkg.resolveDependencies !== "function") {
    console.log("update: not available yet (lib/pkg.mjs resolveDependencies not implemented)");
    return;
  }
  const dir = process.cwd();
  const loaded = pkg.loadPackage(dir);
  const manifest = loaded.manifest;
  const reg = await loadLib("registry.mjs");
  const result = pkg.resolveDependencies(manifest, reg);
  if (!result.ok) {
    console.log("update: dependency conflicts detected:");
    for (const c of result.conflicts || []) console.log(`  ${c}`);
    return;
  }
  console.log(`update: resolved ${Object.keys(result.graph || {}).length} package(s)`);
  for (const [name, info] of Object.entries(result.graph || {})) {
    console.log(`  ${name}@${info.version}`);
  }
}

async function cmdUninstall(args) {
  const name = args[0];
  if (!name) { console.log("usage: ace uninstall <pkg>"); return; }
  const pkg = await loadLib("pkg.mjs");
  if (!pkg) {
    console.log("uninstall: pkg not available yet (lib/pkg.mjs not found)");
    return;
  }
  const dir = process.cwd();
  const loaded = pkg.loadPackage(dir);
  const manifest = loaded.manifest;
  if (!manifest.dependencies || !manifest.dependencies[name]) {
    console.log(`uninstall: "${name}" is not a dependency`);
    return;
  }
  delete manifest.dependencies[name];
  writeJson(path.join(dir, "package.json"), manifest);
  console.log(`Uninstalled ${name}.`);
}

async function cmdSecretSet(args) {
  const name = args[0];
  if (!name) { console.log("usage: ace secret set <name>"); return; }
  const dir = process.cwd();
  const secretsDir = path.join(dir, ".ace", "secrets");
  ensureDir(secretsDir);

  // Read value from stdin without echoing
  const value = await new Promise((resolve) => {
    if (process.stdin.isTTY) {
      // Interactive: use readline with muted output
      import("node:readline").then(({ createInterface }) => {
        const rl = createInterface({ input: process.stdin, output: process.stdout });
        rl.question(`Enter value for ${name}: `, (answer) => {
          rl.close();
          resolve(answer.trim());
        });
      });
    } else {
      // Piped: read all stdin
      let buf = "";
      process.stdin.setEncoding("utf8");
      process.stdin.on("data", (chunk) => { buf += chunk; });
      process.stdin.on("end", () => resolve(buf.trim()));
    }
  });

  if (!value) {
    console.log("secret set: empty value — aborted");
    return;
  }
  fs.writeFileSync(path.join(secretsDir, name), value + "\n", { mode: 0o600 });
  console.log(`Secret "${name}" stored in .ace/secrets/${name}`);
}

async function cmdActivity() {
  const rt = await loadLib("runtime.mjs");
  if (!rt) {
    console.log("activity: runtime not available yet (lib/runtime.mjs not found)");
    return;
  }
  const dir = process.cwd();
  const agents = rt.getAgents(dir);
  const tasks = rt.getTasks(dir);

  const working = agents.filter((a) => a.status === "working");
  const idle = agents.filter((a) => a.status === "idle");
  const queued = tasks.filter((t) => t.status === "queued" || t.status === "pending");

  console.log("NOW:");
  if (!working.length) console.log("  (no agents working)");
  for (const a of working) console.log(`  ${a.id} (${a.role}) — task: ${a.task || "—"}`);

  console.log("NEXT:");
  if (!queued.length) console.log("  (no tasks queued)");
  for (const t of queued) console.log(`  ${t.id} — ${t.title} (priority: ${t.priority || "—"})`);

  if (idle.length) console.log(`IDLE: ${idle.length} agent(s)`);
}

async function cmdLogs(args) {
  const limitIdx = args.indexOf("--limit");
  const limit = limitIdx !== -1 && args[limitIdx + 1] ? parseInt(args[limitIdx + 1], 10) : 20;

  const eventsPath = path.join(process.cwd(), ".ace", "events.jsonl");
  if (!fs.existsSync(eventsPath)) { console.log("No logs yet."); return; }
  const lines = fs.readFileSync(eventsPath, "utf8").trim().split("\n").filter(Boolean);
  const recent = lines.slice(-limit);
  for (const line of recent) {
    const ev = JSON.parse(line);
    console.log(`  [${ev.timestamp}] ${ev.type} — ${ev.actor}${ev.task ? ` (task: ${ev.task})` : ""}`);
  }
}

async function cmdRestart() {
  const rt = await loadLib("runtime.mjs");
  if (!rt) {
    console.log("restart: runtime not available yet (lib/runtime.mjs not found)");
    return;
  }
  const dir = process.cwd();
  const statePath = path.join(dir, ".ace", "state.json");
  if (typeof rt.recover === "function" && fs.existsSync(statePath)) {
    rt.recover(dir);
  }
  rt.setStatus(dir, "ready");
  rt.appendEvent(dir, {
    id: `evt_${crypto.randomBytes(6).toString("hex")}`,
    timestamp: new Date().toISOString(),
    type: "orchestrator.restarted",
    actor: "orchestrator",
    task: null,
    metadata: {},
  });
  console.log("Runtime restarted.");
}

// ---------------------------------------------------------------------------
// verify — run configured package.json scripts (PAW parity: `paw verify`)
// ---------------------------------------------------------------------------

const VERIFY_CHECK_NAMES = ["lint", "typecheck", "test", "build"];

function workspaceInitialized(dir) {
  const pkg = readJson(path.join(dir, "package.json"));
  return Boolean(pkg && pkg.ace);
}

function writeStructuredError(payload) {
  process.stderr.write(JSON.stringify(payload, null, 2) + "\n");
}

function notInitialized(cmd) {
  writeStructuredError({
    code: "PROJECT_NOT_INITIALIZED",
    message: `${cmd} requires an initialized ACE workspace (package.json with an "ace" key).`,
    recoverable: true,
    suggestions: ["Run `ace init` first"],
  });
  process.exitCode = 1;
}

/**
 * Run the configured verification scripts. Zero-dependency: each script is
 * executed exactly as npm would run it (`npm run <name>`), with output
 * captured so callers control their own stdout — this function never prints.
 * Scripts that are not configured are an honest pass, never a fake one.
 */
function runVerifyChecks(dir, only) {
  const pkg = readJson(path.join(dir, "package.json")) || {};
  const scripts = pkg.scripts || {};
  const wanted = only ? [only] : VERIFY_CHECK_NAMES;
  const checks = [];
  for (const name of wanted) {
    if (typeof scripts[name] !== "string") {
      checks.push({ name, configured: false, ok: true });
      continue;
    }
    const r = spawnSync("npm", ["run", name], {
      cwd: dir,
      encoding: "utf8",
      shell: process.platform === "win32",
    });
    if (r.error) {
      checks.push({ name, configured: true, ok: false, exitCode: null, detail: r.error.message });
      continue;
    }
    const ok = r.status === 0;
    const out = `${r.stderr || ""}\n${r.stdout || ""}`.trim();
    const tail = out.split("\n").filter(Boolean).slice(-3).join(" | ");
    checks.push({
      name,
      configured: true,
      ok,
      exitCode: r.status,
      ...(ok ? {} : { detail: tail.slice(0, 300) }),
    });
  }
  return {
    checks,
    ok: checks.every((c) => c.ok),
    configured: checks.some((c) => c.configured),
  };
}

async function cmdVerify(args) {
  const dir = process.cwd();
  if (!workspaceInitialized(dir)) return notInitialized("verify");

  const json = args.includes("--json");
  const selector = args.find((a) => !a.startsWith("--"));
  if (selector !== undefined && !VERIFY_CHECK_NAMES.includes(selector)) {
    writeStructuredError({
      code: "COMMAND_NOT_FOUND",
      message: `Unknown verify target: ${selector}`,
      recoverable: true,
      suggestions: [
        `Use one of: ${VERIFY_CHECK_NAMES.join(", ")}`,
        "Or run `ace verify` with no target to run every configured check",
      ],
    });
    process.exitCode = 2;
    return;
  }

  const result = runVerifyChecks(dir, selector);
  const note = result.configured
    ? undefined
    : "no verification scripts configured — honest pass";

  if (json) {
    printJson({ command: "verify", ...(note ? { note } : {}), checks: result.checks, ok: result.ok });
  } else if (!result.configured) {
    console.log("verify: PASS — no verification scripts configured (lint/typecheck/test/build)");
  } else {
    const ran = result.checks.filter((c) => c.configured).length;
    console.log(`verify: ${result.ok ? "PASS" : "FAIL"} — ${ran} script(s) run`);
    for (const c of result.checks) {
      if (!c.configured) {
        console.log(`  - ${c.name} (none configured)`);
      } else {
        console.log(`  ${c.ok ? "✓" : "✗"} ${c.name}${c.ok ? "" : ` (exit ${c.exitCode})${c.detail ? ` — ${c.detail}` : ""}`}`);
      }
    }
  }
  if (!result.ok) process.exitCode = 1;
}

// ---------------------------------------------------------------------------
// autopilot — the always-on loop (PAW parity: `paw autopilot`)
//
//   ace autopilot [status] [--json]
//   ace autopilot on  [--interval <sec>] [--mission "<text>"]
//   ace autopilot run [--interval <sec>] [--max-cycles <n>] [--json]
//   ace autopilot off
//
// One cycle walks the state machine recorded in `.ace/autopilot.json`:
//   PLAN → EXECUTE → VERIFY → CHECKPOINT → SUCCESS | FAIL → REPLAN → (next)
//
// Scope honesty (v0): EXECUTE runs the two commands the workspace already
// trusts — verification (`ace verify`'s checks) and a checkpoint (snapshot) —
// through the same code paths, and adds the loop, the state file and the
// history. A mission passed to `on`/`run` is recorded and reported; task
// decomposition is NOT implemented — status says so instead of pretending.
// A cycle never edits the repository.
// ---------------------------------------------------------------------------

const AUTOPILOT_DEFAULT_INTERVAL = 300;
const AUTOPILOT_HISTORY_LIMIT = 25;
const AUTOPILOT_VALUE_FLAGS = new Set(["--interval", "--mission", "--max-cycles"]);

function autopilotFile(dir) { return path.join(dir, ".ace", "autopilot.json"); }
function autopilotLogFile(dir) { return path.join(dir, ".ace", "autopilot.log"); }

function defaultAutopilotFile() {
  return {
    version: 1,
    state: "IDLE",
    pid: null,
    intervalSec: AUTOPILOT_DEFAULT_INTERVAL,
    mission: null,
    cycleCount: 0,
    lastCycle: null,
    history: [],
    humanGate: [],
    updatedAt: new Date().toISOString(),
  };
}

function loadAutopilotFile(dir) {
  const parsed = readJson(autopilotFile(dir));
  if (!parsed) return defaultAutopilotFile();
  return { ...defaultAutopilotFile(), ...parsed };
}

function saveAutopilotFile(dir, file) {
  file.updatedAt = new Date().toISOString();
  writeJson(autopilotFile(dir), file);
}

function pidAlive(pid) {
  if (pid === null || typeof pid !== "number") return false;
  try { process.kill(pid, 0); return true; } catch { return false; }
}

function clampInterval(raw, fallback) {
  if (raw === undefined) return fallback;
  const n = Number.parseInt(String(raw), 10);
  if (!Number.isFinite(n)) return fallback;
  return Math.min(86_400, Math.max(10, n));
}

function parseAutopilotArgs(argv) {
  const positionals = [];
  const flags = {};
  for (let i = 0; i < argv.length; i++) {
    const t = argv[i];
    if (t.startsWith("--")) {
      const eq = t.indexOf("=");
      if (eq >= 0) { flags[t.slice(0, eq)] = t.slice(eq + 1); continue; }
      const next = argv[i + 1];
      if (AUTOPILOT_VALUE_FLAGS.has(t) && next !== undefined && !next.startsWith("-")) {
        flags[t] = next;
        i++;
        continue;
      }
      flags[t] = true;
      continue;
    }
    positionals.push(t);
  }
  return { positionals, flags };
}

/** Checkpoint step: ACE's checkpoint IS the snapshot (honest skip if the runtime is absent). */
async function runCheckpointStep(dir) {
  const rt = await loadLib("runtime.mjs");
  if (!rt || typeof rt.snapshot !== "function") {
    return { ran: false, reason: "runtime not available (lib/runtime.mjs)" };
  }
  try {
    const snap = rt.snapshot(dir);
    return { ran: true, exitCode: 0, snapshot: snap.id };
  } catch (err) {
    return { ran: true, exitCode: 1, reason: String((err && err.message) || err) };
  }
}

/**
 * One cycle: PLAN → EXECUTE → VERIFY → CHECKPOINT → SUCCESS | FAIL → REPLAN.
 * Never edits the repository; verify/checkpoint run through the same code
 * paths a manual run uses, and neither prints — so `run --json` can keep
 * stdout to exactly ONE document.
 */
async function runAutopilotCycle(dir, file) {
  const startedAt = new Date().toISOString();
  const transitions = ["PLAN", "EXECUTE"];
  file.state = "PLAN";
  file.cycleCount += 1;

  const verify = runVerifyChecks(dir);
  transitions.push("VERIFY");
  file.state = "VERIFY";

  const checkpoint = await runCheckpointStep(dir);
  transitions.push("CHECKPOINT");
  file.state = "CHECKPOINT";

  const checkpointOk = checkpoint.ran ? checkpoint.exitCode === 0 : true;
  const ok = verify.ok && checkpointOk;
  const finalState = ok ? "SUCCESS" : "FAIL";
  transitions.push(finalState, "REPLAN");
  file.state = finalState;

  const record = {
    cycle: file.cycleCount,
    startedAt,
    finishedAt: new Date().toISOString(),
    transitions,
    verifyOk: verify.ok,
    checks: verify.checks.map((c) => ({ name: c.name, configured: c.configured, ok: c.ok })),
    checkpoint,
    ok,
  };
  file.lastCycle = record;
  file.history = [...file.history, record].slice(-AUTOPILOT_HISTORY_LIMIT);
  saveAutopilotFile(dir, file);
  return record;
}

function autopilotPayload(dir, file) {
  const running = pidAlive(file.pid);
  return {
    command: "autopilot",
    armed: file.state !== "IDLE",
    state: file.state,
    loopRunning: running,
    pid: running ? file.pid : null,
    intervalSec: file.intervalSec,
    mission: file.mission,
    missionDecomposed: false,
    cycleCount: file.cycleCount,
    lastCycle: file.lastCycle,
    humanGate: file.humanGate,
    repository: path.basename(dir),
    updatedAt: file.updatedAt,
    note: "v0: each cycle runs verification then a snapshot checkpoint and records the result. A recorded mission is reported, not executed — task decomposition arrives with the planner.",
  };
}

function renderAutopilotStatus(payload) {
  const on = payload.loopRunning === true;
  const mission = typeof payload.mission === "string" && payload.mission.length > 0
    ? payload.mission
    : "(none — verify loop)";
  const last = payload.lastCycle;
  const lastLine = last === null
    ? "never ran"
    : `#${last.cycle} at ${last.finishedAt} · verify ${last.verifyOk ? "PASS" : "FAIL"} · checkpoint ${
        last.checkpoint.ran
          ? (last.checkpoint.exitCode === 0 ? "PASS" : "FAIL")
          : `skipped (${last.checkpoint.reason || "n/a"})`
      }`;
  const gate = (payload.humanGate || []).length;
  return [
    "┌─────────────────────────────────────────────────────┐",
    `│ ACE AUTOPILOT                                  ${on ? "ON " : "OFF"} │`,
    "├─────────────────────────────────────────────────────┤",
    `│ Repository: ${String(payload.repository).padEnd(42)}│`,
    `│ Mission: ${mission.slice(0, 44).padEnd(45)}│`,
    `│ State: ${String(payload.state).padEnd(12)} cycle ${String(payload.cycleCount).padEnd(22)}│`,
    `│ Loop: ${on ? `pid ${payload.pid}, every ${payload.intervalSec}s` : "not running"}${"".padEnd(on ? 26 : 35)}│`,
    `│ Last: ${lastLine.slice(0, 47).padEnd(48)}│`,
    `│ Human gate: ${String(gate).padEnd(41)}│`,
    "├─────────────────────────────────────────────────────┤",
    "│ v0: verify + checkpoint per cycle; mission recorded, │",
    "│ not decomposed. A blocked branch never stops the run. │",
    "└─────────────────────────────────────────────────────┘",
  ].join("\n");
}

function autopilotSleep(ms) {
  return new Promise((resolve) => setTimeout(resolve, ms));
}

async function cmdAutopilot(args) {
  const dir = process.cwd();
  if (!workspaceInitialized(dir)) return notInitialized("autopilot");

  const { positionals, flags } = parseAutopilotArgs(args);
  const json = flags["--json"] === true;
  const sub = positionals[0] || "status";
  const file = loadAutopilotFile(dir);
  const emit = (text, payload) => {
    process.stdout.write(json ? `${JSON.stringify(payload, null, 2)}\n` : text);
  };

  if (sub === "status") {
    const payload = autopilotPayload(dir, file);
    emit(`${renderAutopilotStatus(payload)}\n`, payload);
    return;
  }

  if (sub === "on") {
    if (pidAlive(file.pid)) {
      const payload = { ...autopilotPayload(dir, file), message: "already running" };
      emit(`autopilot already running (pid ${file.pid})\n`, payload);
      return;
    }
    file.intervalSec = clampInterval(flags["--interval"], file.intervalSec);
    const mission = flags["--mission"];
    if (typeof mission === "string" && mission.length > 0) file.mission = mission;
    file.state = "PLAN";
    saveAutopilotFile(dir, file);

    const logFd = fs.openSync(autopilotLogFile(dir), "a");
    try {
      const child = spawn(
        process.execPath,
        [HERE_FILE, "autopilot", "run", "--interval", String(file.intervalSec)],
        { cwd: dir, env: process.env, detached: true, stdio: ["ignore", logFd, logFd] }
      );
      child.unref();
      file.pid = child.pid ?? null;
    } finally {
      fs.closeSync(logFd);
    }
    saveAutopilotFile(dir, file);
    const payload = autopilotPayload(dir, file);
    emit(
      `autopilot ON — pid ${file.pid}, first cycle starts now, then every ${file.intervalSec}s (log: ${path.relative(dir, autopilotLogFile(dir))})\n`,
      payload
    );
    return;
  }

  if (sub === "off") {
    const running = pidAlive(file.pid);
    if (running && file.pid !== null) {
      try { process.kill(file.pid, "SIGTERM"); } catch { /* exited between check and signal — state below is still truthful */ }
    }
    file.state = "IDLE";
    file.pid = null;
    saveAutopilotFile(dir, file);
    const payload = { ...autopilotPayload(dir, file), stopped: running };
    emit(
      running
        ? `autopilot OFF — pid stopped after ${file.cycleCount} cycle(s)\n`
        : "autopilot was not running\n",
      payload
    );
    return;
  }

  if (sub === "run") {
    const maxRaw = flags["--max-cycles"];
    const parsedMax = maxRaw === undefined ? Number.NaN : Number.parseInt(String(maxRaw), 10);
    const maxCycles = Number.isFinite(parsedMax) ? Math.max(1, parsedMax) : Number.POSITIVE_INFINITY;
    file.intervalSec = clampInterval(flags["--interval"], file.intervalSec);
    if (file.state === "IDLE") file.state = "PLAN";
    saveAutopilotFile(dir, file);

    let cycles = 0;
    while (true) {
      const record = await runAutopilotCycle(dir, file);
      cycles += 1;
      if (json) {
        process.stdout.write(`${JSON.stringify({ command: "autopilot cycle", cycle: record }, null, 2)}\n`);
      } else {
        process.stdout.write(
          `cycle ${record.cycle}: ${record.ok ? "SUCCESS" : "FAIL"} · verify ${record.verifyOk ? "PASS" : "FAIL"} · checkpoint ${
            record.checkpoint.ran
              ? (record.checkpoint.exitCode === 0 ? `snapshot ${record.checkpoint.snapshot || "ok"}` : "FAIL")
              : `skipped: ${record.checkpoint.reason || "n/a"}`
          }\n`
        );
      }
      if (cycles >= maxCycles) break;
      await autopilotSleep(file.intervalSec * 1000);
    }
    if (file.lastCycle && file.lastCycle.ok !== true) process.exitCode = 1;
    return;
  }

  writeStructuredError({
    code: "COMMAND_NOT_FOUND",
    message: `Unknown autopilot subcommand: ${sub}`,
    recoverable: true,
    suggestions: ["Use: ace autopilot [status] | on | run | off"],
  });
  process.exitCode = 2;
}

// ---------------------------------------------------------------------------
// Router
// ---------------------------------------------------------------------------

const COMMANDS = {
  init: cmdInit,
  install: cmdInstall,
  list: cmdList,
  info: cmdInfo,
  search: cmdSearch,
  run: cmdRun,
  status: cmdStatus,
  context: cmdContext,
  agents: cmdAgents,
  tasks: cmdTasks,
  events: cmdEvents,
  stop: cmdStop,
  snapshot: cmdSnapshot,
  restore: cmdRestore,
  compose: cmdCompose,
  doctor: cmdDoctor,
  update: cmdUpdate,
  uninstall: cmdUninstall,
  activity: cmdActivity,
  logs: cmdLogs,
  restart: cmdRestart,
  verify: cmdVerify,
  autopilot: cmdAutopilot,
};

async function main() {
  const args = process.argv.slice(2);
  const cmd = args[0];

  if (!cmd || cmd === "--help" || cmd === "-h" || cmd === "help") {
    console.log(`ACE — Agentic Compute Environment CLI

Usage: ace <command> [options]

Commands:
  init [--name <n>]      Scaffold package.json (with ace key) + ace-lock.json + README
  install [<pkg>]       Install from local registry, or git ref
  list                   List installed packages
  info <pkg>             Show package detail
  search <q>             Search local registry
  run                    Start runtime
  status                 Show human-readable status
  context [--json]       Show environment context
  agents                 List agents
  tasks                  List tasks
  events [--limit N]     Show event stream (default 20)
  stop                   Stop runtime
  snapshot               Create snapshot
  restore <id>           Restore snapshot
  compose [--json]       Print composed spec (extends + overrides + capabilities)
  doctor [--json]        Environment diagnostics
  update                 Update dependencies per version constraints
  uninstall <pkg>        Remove a dependency from package.json
  secret set <name>      Inject a secret into .ace/secrets/<name>
  activity               NOW / NEXT activity stream
  logs [--limit N]       Tail the event log (default 20)
  restart                Recover + continue
  verify [check] [--json] Run configured verification (lint/typecheck/test/build)
  autopilot [status]     The always-on loop: verify + checkpoint per cycle [--json]
  autopilot on           Start the detached loop (--interval N, --mission "text")
  autopilot run          Run cycles here, then exit (--max-cycles N) [--json]
  autopilot off          Stop exactly the recorded pid

Options:
  --name <n>             Target directory for init
  --limit N              Limit for events/logs command
  --interval N           Autopilot cycle interval in seconds (min 10, default 300)
  --mission "<text>"     Mission recorded by autopilot on (not decomposed)
  --max-cycles N         Stop autopilot run after N cycles
  --json                 JSON output for context/compose/doctor/verify/autopilot
`);
    return;
  }

  const handler = COMMANDS[cmd];
  if (!handler) {
    // Handle two-word commands: ace secret set <name>
    if (cmd === "secret" && args[1] === "set") {
      try { await cmdSecretSet(args.slice(2)); } catch (err) { console.error(`ace secret set: ${err.message}`); process.exitCode = 1; }
      return;
    }
    console.log(`Unknown command: ${cmd}`);
    console.log("Run `ace --help` for usage.");
    process.exitCode = 1;
    return;
  }

  try {
    await handler(args.slice(1));
  } catch (err) {
    console.error(`ace ${cmd}: ${err.message}`);
    process.exitCode = 1;
  }
}

main();
